add product list with NavigationSplitView
MargotPasquali/Joiefull pull request #1
Opened 2024-12-27 13:19 UTC by MargotPasquali

first backlog user story

2024-12-27 13:35 UTC, damien-rivet requested changes
Code LGTM but I left a few comments to fix.

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullModels/JoiefullModels/JoiefullModels.h
**suggestion (blocking)**: This file is not useful anymore, we should delete it.

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +public final class Clothes: Identifiable, Decodable, Hashable, Equatable {
**question (blocking)**: Why did you use a class here? We should strive to use `struct` as mush as possible.

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +            case .accessories: return 3
**suggestion (non-blocking)**: You can remove the `return` statement.

```suggestion
            switch self {
            case .tops: 0
            case .bottoms: 1
            case .shoes: 2
            case .accessories: 3
```

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +    public var id: Int
**suggestion (blocking)**: We should use `let` as much as possible.

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullService/NetworkManager.swift
> +    private var urlSession: URLSession
**suggestion (blocking)**: We should use `let` as much as possible.

2024-12-27 13:35 UTC, damien-rivet commented on JoiefullService/NetworkManager.swift
> +    }
**suggestion (blocking)**: For a singleton, the `init` must be private.

2024-12-27 13:37 UTC, damien-rivet commented on JoiefullService/NetworkManager.swift
> +    private var urlSession: URLSession
Done!

2024-12-27 13:52 UTC, damien-rivet approved these changes
👍

2024-12-30 15:20 UTC, damien-rivet requested changes
Left many comments, some parts needs to be refactored before approval.

2024-12-30 15:20 UTC, damien-rivet commented on Sources/ViewModels/ProductListViewModel.swift
> +    }
**suggestion (blocking)**: Those should be located at the service level, not in the viewModel. The VM should handle those case to return a user friendly error.

2024-12-30 15:20 UTC, damien-rivet commented on Sources/ViewModels/ProductListViewModel.swift
> +    @Published var isLoading: Bool = false
**nitpick (non-blocking)**: You can omit some things:

```suggestion
    @Published var products = [Clothes]()
    @Published var isLoading = false
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/ViewModels/ProductListViewModel.swift
> +    init(Service: Service = RemoteService()) {
**suggestion (blocking)**: Use camelCase for naming.

```suggestion
    init(service: Service = RemoteService()) {
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/ViewModels/ProductListViewModel.swift
> +    init(Service: Service = RemoteService()) {
**suggestion (blocking)**: We should avoid generic names as it gives no information on the object itself.

```suggestion
    init(productService: ProductService = RemoteProductService()) {
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/ViewModels/ProductListViewModel.swift
> +            products = productList
**nitpick (non-blocking)**: A slight improvement:

```suggestion
            products = try await Service.fetchClothesData()
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/Categories/ListItemView.swift
> +                            .frame(width: 198, height: 198)
**suggestion (blocking)**: The frame size should be stored in a constant somewhere.

```suggestion
                            .frame(width: imageSize, height: imageSize)
                    case .success(let image):
                        image
                            .resizable()
                            .aspectRatio(contentMode: .fill)
                            .frame(width: imageSize, height: imageSize)
                            .cornerRadius(20)
                    case .failure:
                        Image(systemName: "photo")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(width: imageSize, height: imageSize)
```

Otherwise you'll have to set it multiple times when changing its value.

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/Categories/ListItemView.swift
> +                Text(String(format: "%.1f", clothes.price))
**suggestion (blocking)**: You are using the product's `price` instead of its rating.

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/Categories/ListItemView.swift
> +    let clothes: Clothes
**suggestion (blocking)**: It should be `private` and it's not necessarily a clothing item, could be an accessory or anything else, `product` would be a better name.

```suggestion
    private let product: Product
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/Categories/ListRowView.swift
> +    }
**suggestion (blocking)**: We should strive to make the code as readable as possible:

```suggestion
    // MARK: - Constants

    private let products: [Product]

    // MARK: - Properties

    @Binding
    private var selectedProduct: Product?

    // MARK:- Views

    var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 15) {
                ForEach(products) { product in
                    NavigationLink(destination: ProductDetailView(product: product), tag: product, selection: $selectedProduct) {
                        ListItemView(product: product)
                    }
                }
            }
        }
    }
```

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/DetailView.swift
**suggestion (blocking)**: File's name should not be generic.

`ProductDetailsView.swift` would be a better name.

2024-12-30 15:20 UTC, damien-rivet commented on Sources/Views/DetailView.swift
> +    var clothes: Clothes // Propriété pour afficher les détails d'un vêtement
**suggestion (blocking)**: The naming of this variable can be misinterpreted. Also, comment should not be in french and it's not very useful.

```suggestion
    private let product: Product
```

2024-12-30 15:20 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +public struct Clothes: Identifiable, Decodable, Hashable {
**suggestion (blocking)**: Object's names must always be singular and correctly named.

```suggestion
public struct Product: Identifiable, Decodable, Hashable {
```

2024-12-30 15:20 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +// MARK: - Clothes Struct
**nitpick (non-blocking)**: Comment can be removed as it adds nothing.

2024-12-30 15:20 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +    public enum Category: String, Codable, Comparable, Hashable {
**nitpick (non-blocking)**: `Codable` adoption is not needed as you do not encode this value, `Decodable` is more relevant here.

2024-12-30 15:20 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
> +        public var imageUrl: URL? {
**nitpick (non-blocking)**: For well-known acronyms, always keep the casing.

```suggestion
        public var imageURL: URL? {
```

2024-12-30 15:20 UTC, damien-rivet commented on JoiefullModels/Clothes.swift
**suggestion (blocking)**: This model does far too much things, it's used for both display and decoding from JSON.

It should be two different objects, one for the decoding part (in the network layer) and another one in the models part that is only used to convey data around (Data Transfer Obect, DTO).

2024-12-30 15:50 UTC, MargotPasquali commented on Sources/ViewModels/ProductListViewModel.swift
> +    }
it's good for me, I think, I should handle the viewmodel error in a different way.

2024-12-30 17:18 UTC, MargotPasquali commented on JoiefullModels/Clothes.swift
Okay, I have now three files, a DTO file, a file for the app and a file dedicated to images

2025-01-02 15:09 UTC, MargotPasquali commented on Sources/Views/Categories/ListItemView.swift
> +                Text(String(format: "%.1f", clothes.price))
As the rating data is missing in the dataset, I put a default value. In the next commit, I will implemente Persistencedata for the product rating feature.

2025-01-09 12:57 UTC, damien-rivet approved these changes
Code looks good to me 👍

2025-01-09 13:03 UTC, merged